[build-system]
requires = ["setuptools >= 65.5.0"]
build-backend = "setuptools.build_meta"

[project]
name = "task-latent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "nilearn>=0.14.0",
    "pybids>=0.22.0",
]

[tool.setuptools.packages.find]
include = ["task_latent"]
