[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "task-latent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "nilearn>=0.14.0",
    "pybids>=0.22.0",
    "pandas==2.3.2",
    "numpy<2.5"
]

[tool.setuptools.packages.find]
include = ["task_latent"]
